/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ae36c046fd12874bde1a526e0e06f2d0)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	POOL_ROOMS: DurableObjectNamespace<import("./server/worker").PoolRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server/worker");
		durableNamespaces: "PoolRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
